# YOUR NAME OR TITLE OF YOUR SITE
name: DEA ROKHMATUN IRADEWA

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Iradewa. Coffee-Lover

# YOUR/BRAND IMAGE URL
Image_URL: https://iradewa.github.io/me.webp?s=500

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com/dr.iradewa
    Username: dr.iradewa
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: 
    Username: iradewa
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: 
    Username: iradewa
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

   

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/caramita
    Username: caramita
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

   
    # EMAIL
  - Name: Email
    URL: 'mailto:iradewa@duck.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


    # MESSENGER
  - Name: Messenger
    URL: 
    Username: theharshtrivedi
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

  

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #####   Icon-Class: fab fa-whatsapp

    # TELEGRAM
 - Name: Telegram
 URL: http://telegram.me
 Username: iradewa
Color: '#0088cc'
 Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  ##########- Name: Snapchat
   ##### URL: https://www.snapchat.com/add
   ###### Username: 'harsh98trivedi'
  #######  Color: '#FFFC00'
  ########  Text_Color: '#000000'
  #########  Icon-Class: fab fa-snapchat-ghost

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  ##- Name: Pinterest
   ### URL: https://pinterest.com
   #### Username: 'harsh98trivedi'
  #####  Color: '#E60023'
  ######  Icon-Class: fab fa-pinterest

    # BEHANCE
 ####### - Name: Behance
  #  URL: https://www.behance.net
  ##  Username: harsh98trivedi
 ###   Color: '#1769ff'
 ####   Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
#  - Name: DeviantArt
#####    URL: https://www.deviantart.com
####    Username: harshtrivedi
###    Icon-Class: fab fa-deviantart
 ##   Color: '#05CC46'
  #  Text_Color: '#ffffff'

 

  #    # TIKTOK
  - Name: TikTok
     URL: https://www.tiktok.com/@asagampil
    Username: asagampil
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

  ######
    # DEV.TO
  ######- Name: Dev.to
  #####  URL: 'https://dev.to'
  ####  Username: harsh98trivedi
  ###  Icon-Class: fab fa-dev
  ##  Color: '#ffffff'
  #  Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  ######- Name: BuyMeACoffee
#####    URL: 'https://buymeacoffee.com'
 ####   Username: harshtrivedi
 ###   Icon-Class: fas fa-mug-hot
 ##   Color: '#FFDD00'
 #   Text_Color: '#000000'

    # CUSTOM LINK
 - Name: Shop on Shopee
URL: https://shopee.co.id/labanstore
Icon-Class: fas fa-link
  Color: '#ffb142'
 Text_Color: '#ffffff'

#####  - Name: Links
 ####   URL: https://github.com/harsh98trivedi/links
 ###   Icon-Class: fas fa-link
 ##   Color: '#d94869'
 #   Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
